services:
  frontend:
    build:
      context: Frontend
    ports:
      - "5000:3000"
  backend:
    build:
      context: Backend
    volumes:
      - db-data:/backend/data/*
    ports:
      - "4000:3000"

volumes:
  db-data:
    driver: local
